"""Frozen BV-income diagnostic: official RBC plus joint two-side covariance.

No causal clearance is generated by this program. See assignment_rd_protocol.md
sections 10–11. The primary h=b=1000 is fixed before these outcomes are read.
"""
from pathlib import Path
import sys,json,hashlib,datetime,importlib.metadata,warnings,contextlib,io
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'.vendor_rd'))
sys.path.insert(1,str(ROOT/'.vendor'))
import numpy as np,pandas as pd,networkx as nx
from scipy import stats
from rdrobust import rdrobust
from statsmodels.stats.multitest import multipletests
import duckdb

OUT=ROOT/'data/processed';TAB=ROOT/'results/tables';REP=ROOT/'reports'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()

def components(selected,q,kind):
    graph=nx.Graph()
    for bv in q.index:graph.add_node('B:'+str(bv))
    for r in selected[selected.bassin_2022_cog2023.isin(q.index)].itertuples():
        if kind in ('epci','joint') and str(r.epci_2023).isdigit() and len(str(r.epci_2023))==9:
            graph.add_edge('B:'+r.bassin_2022_cog2023,'E:'+r.epci_2023)
        if kind in ('department','joint'):graph.add_edge('B:'+r.bassin_2022_cog2023,'D:'+r.department)
    mapping={n:i for i,g in enumerate(nx.connected_components(graph)) for n in g if n.startswith('B:')}
    g=np.array([mapping['B:'+str(v)] for v in q.index]);sizes=pd.Series(g).value_counts()
    return g,{'groups':len(sizes),'max_group_units':int(sizes.max()),'max_group_share':float(sizes.max()/len(q)),
              'size_concentration_equivalent_groups':float(len(q)**2/(sizes**2).sum()),
              'cross_cutoff_groups':sum(len(set(q.x.to_numpy()[g==c]>=0))==2 for c in sizes.index)}

def linear_fit(x,Y,h,degree,cluster=None):
    """Two separate polynomials in one model, including both-side cluster scores."""
    x=np.asarray(x)/h;Y=np.asarray(Y)
    if Y.ndim==1:Y=Y[:,None]
    right=(x>=0).astype(float);w=1-np.abs(x)
    X=np.column_stack([np.power(x,j)*(1-right) for j in range(degree+1)]+
                      [np.power(x,j)*right for j in range(degree+1)])
    if np.linalg.matrix_rank(X)!=X.shape[1]:raise RuntimeError('Polynomial matrix rank deficient')
    inv=np.linalg.inv(X.T@(w[:,None]*X));beta=inv@(X.T@(w[:,None]*Y))
    L=np.zeros(X.shape[1]);L[0]=-1;L[degree+1]=1
    omega=L@inv@(X.T*w);theta=L@beta
    residual=Y-X@beta;hat=w*np.einsum('ij,jk,ik->i',X,inv,X)
    if np.max(hat)>=1-1e-8:raise RuntimeError('Single unit determines a fitted intercept')
    score=omega[:,None]*residual/(1-hat[:,None]);cov=score.T@score
    if cluster is not None:
        cs=pd.DataFrame(omega[:,None]*residual).groupby(cluster).sum().to_numpy()
        G=len(cs);n=len(x);k=X.shape[1]
        cov=cs.T@cs*(G/(G-1))*((n-1)/(n-k)) if G>1 else np.full_like(cov,np.nan)
    return theta,cov,{'max_leverage':float(hat.max()),'score':score,'rank':int(np.linalg.matrix_rank(cov))}

def official(y,x,h):
    messages=io.StringIO()
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        with contextlib.redirect_stdout(messages):
            z=rdrobust(y=y,x=x,c=0,p=1,q=2,h=h,b=h,kernel='triangular',masspoints='adjust',vce='hc3',level=95)
    return {'conventional':float(z.coef.loc['Conventional'].iloc[0]),'bias_corrected':float(z.coef.loc['Robust'].iloc[0]),
            'se_rbc_hc3':float(z.se.loc['Robust'].iloc[0]),'ci_low_hc3':float(z.ci.loc['Robust'].iloc[0]),
            'ci_high_hc3':float(z.ci.loc['Robust'].iloc[1]),'p_hc3':float(z.pv.loc['Robust'].iloc[0]),
            'high_income_units':int(z.N_h[0]),'eligible_low_income_units':int(z.N_h[1]),
            'warnings':' | '.join([str(v.message) for v in caught]+[messages.getvalue().strip()])}

def main():
    sources=['docs/assignment_rd_protocol.md','src/analysis/bassin_rd.py','data/processed/assignment2024_commune_paths.csv',
             'data/processed/commune_treatment.csv','data/processed/monthly_panel.parquet']
    freeze={'frozen_before_new_outcome_read':True,'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
            'protocol':'V, sections10–11; unique post-level primary; all specified pre periods and radii',
            'software':{n:importlib.metadata.version(n) for n in ['rdrobust','numpy','pandas','scipy','statsmodels','matplotlib']},
            'rdrobust_source':'https://github.com/rdpackages/rdrobust','rdrobust_source_file_sha256':sha(ROOT/'.vendor_rd/rdrobust/rdrobust.py'),
            'source_sha256':{p:sha(ROOT/p) for p in sources},'primary_command':'rdrobust(y,21600-income,c=0,p=1,q=2,h=1000,b=1000,kernel=triangular,masspoints=adjust,vce=hc3)',
            'joint_cluster_variance':'full two-side q2 WLS CR1/t(G−1), not separate-side software variance; no cross-side covariance omitted',
            'support_is_not_causal_clearance':True}
    freeze_path=REP/'bassin_rd_execution_freeze.json'
    if freeze_path.exists():
        original=json.loads(freeze_path.read_text(encoding='utf8'))
        freeze['frozen_before_new_outcome_read']=False
        freeze['rerun_after_prior_execution_attempt']=True
        original.setdefault('rerun_history',[]).append(freeze)
        freeze_path.write_text(json.dumps(original,ensure_ascii=False,indent=2),encoding='utf8')
    else:
        freeze_path.write_text(json.dumps(freeze,ensure_ascii=False,indent=2),encoding='utf8')
    d=pd.read_csv(OUT/'assignment2024_commune_paths.csv',dtype={'commune_code':str,'epci_2023':str,'department':str,'bassin_2022_cog2023':str},low_memory=False)
    meta=pd.read_csv(OUT/'commune_treatment.csv',dtype={'commune_code':str},low_memory=False)
    fixed=set(meta.loc[meta.analysis_stable&meta.metropolitan&meta.prior_zrr_effects.eq(False),'commune_code'])
    s=d[d.commune_code.isin(fixed)&d.actual_epci&d.population_below30000&d.bassin_density_2020.le(65.84)&
        ~d.eligible_A_epci&~d.eligible_A_isolated_commune&~d.eligible_C_department&~d.eligible_D_potential].copy()
    s[['commune_code','bassin_2022_cog2023','epci_2023','department','P20_POP']].to_csv(OUT/'bassin_rd_selected_communes.csv',index=False)
    unit=s.groupby('bassin_2022_cog2023').agg(sample_population=('P20_POP','sum'),sample_communes=('commune_code','size'),
                     income=('bassin_median_income2020','first'),density=('bassin_density_2020','first'))
    unit['x']=21600-unit.income
    unit.to_csv(OUT/'bassin_rd_candidates.csv')
    # First research-outcome read occurs only after the execution freeze above.
    con=duckdb.connect();con.register('selected',s[['commune_code','bassin_2022_cog2023']])
    path=(OUT/'monthly_panel.parquet').as_posix()
    z=con.execute('SELECT s.bassin_2022_cog2023,CAST(p.month AS VARCHAR) AS "month",sum(p.establishment_births) AS births,sum(p.births_without_recorded_continuity) AS without_continuity FROM read_parquet(?) p JOIN selected s USING(commune_code) GROUP BY 1,2 ORDER BY 1,2',[path]).df()
    z['month']=pd.to_datetime(z.month);z['population']=z.bassin_2022_cog2023.map(unit.sample_population)
    z['y']=1000*z.births/z.population;z['y_no_continuity']=1000*z.without_continuity/z.population
    z.to_parquet(OUT/'bassin_rd_monthly_aggregates.parquet',index=False)
    Y=z.pivot(index='bassin_2022_cog2023',columns='month',values='y').reindex(unit.index)
    if Y.isna().any().any():raise RuntimeError('Incomplete fixed BV panel')
    results=[];dependency=[];monthly=[];joint={};official_checks=[]
    pre=Y.columns[(Y.columns>=pd.Timestamp('2019-01-01'))&(Y.columns<=pd.Timestamp('2023-05-01'))]
    periods={'primary_2024H2':(Y.columns.year==2024)&(Y.columns.month>=7)}
    for year in range(2019,2023):periods[f'placebo_{year}H2']=(Y.columns.year==year)&(Y.columns.month>=7)
    for h in [500,750,1000,1500]:
        q=unit[unit.x.abs().lt(h)];yh=Y.reindex(q.index);g,detail=components(s,q,'joint')
        gf,full_detail=components(d,q,'joint')
        for scope,source in [('selected',s),('full',d)]:
            for kind in ['epci','department','joint']:
                _,dt=components(source,q,kind);dependency.append({'bandwidth':h,'scope':scope,'kind':kind,**dt})
        for label,mask in periods.items():
            y=yh.loc[:,mask].mean(axis=1).to_numpy();r=official(y,q.x.to_numpy(),h)
            theta,cov,diag=linear_fit(q.x,y,h,2);tc,vc,_=linear_fit(q.x,y,h,2,g)
            _,vf,_=linear_fit(q.x,y,h,2,gf)
            delta_point=abs(float(theta[0])-r['bias_corrected']);delta_se=abs(float(np.sqrt(cov[0,0]))-r['se_rbc_hc3'])
            official_checks.append({'period':label,'bandwidth':h,'point_difference':delta_point,'se_difference':delta_se})
            if max(delta_point,delta_se)>1e-7:raise RuntimeError('Independent q2/RBC identity failed')
            se=float(np.sqrt(vc[0,0]));G=detail['groups'];crit=stats.t.ppf(.975,G-1)
            sef=float(np.sqrt(vf[0,0]));Gf=full_detail['groups'];critf=stats.t.ppf(.975,Gf-1)
            results.append({'period':label,'bandwidth':h,**r,'joint_se':se,'joint_ci_low':float(theta[0]-crit*se),
                'joint_ci_high':float(theta[0]+crit*se),'joint_p':float(2*stats.t.sf(abs(theta[0]/se),G-1)),
                'full_joint_se':sef,'full_joint_ci_low':float(theta[0]-critf*sef),'full_joint_ci_high':float(theta[0]+critf*sef),
                'full_joint_p':float(2*stats.t.sf(abs(theta[0]/sef),Gf-1)),'full_joint_groups':Gf,
                'joint_groups':G,'max_leverage':diag['max_leverage'],'eligible_distinct_scores':q[q.x>=0].x.nunique(),
                'high_income_distinct_scores':q[q.x<0].x.nunique()})
        if h==1000:
            theta,cov,diag=linear_fit(q.x,yh.to_numpy(),h,2);_,vc,_=linear_fit(q.x,yh.to_numpy(),h,2,g)
            _,vf,_=linear_fit(q.x,yh.to_numpy(),h,2,gf)
            for j,month in enumerate(yh.columns):
                r=official(yh.iloc[:,j].to_numpy(),q.x.to_numpy(),h)
                if max(abs(theta[j]-r['bias_corrected']),abs(np.sqrt(cov[j,j])-r['se_rbc_hc3']))>1e-7:
                    raise RuntimeError('Monthly independent RBC identity failed')
                official_checks.append({'period':'month_'+str(month.date()),'bandwidth':h,
                    'point_difference':abs(theta[j]-r['bias_corrected']),'se_difference':abs(np.sqrt(cov[j,j])-r['se_rbc_hc3'])})
                se=np.sqrt(vc[j,j]);G=detail['groups'];tcrit=stats.t.ppf(.975,G-1)
                monthly.append({'month':str(month.date()),**r,'joint_se':se,'joint_ci_low':theta[j]-tcrit*se,
                    'joint_ci_high':theta[j]+tcrit*se,'joint_p':2*stats.t.sf(abs(theta[j]/se),G-1),
                    'full_joint_se':np.sqrt(vf[j,j])})
            ix=[yh.columns.get_loc(m) for m in pre];coeff=theta[ix]
            for name,v in [('independent_HC3',cov),('joint_CR1',vc),('full_joint_CR1',vf)]:
                V=v[np.ix_(ix,ix)];rank=np.linalg.matrix_rank(V);wald=float(coeff@np.linalg.pinv(V)@coeff)
                joint[name]={'restrictions':len(ix),'covariance_rank':int(rank),'wald':wald,
                    'p_chi2_rank_reference':float(stats.chi2.sf(wald,rank)),
                    'full_restrictions_test_available':bool(rank==len(ix)),
                    'warning':'Pseudoinverse statistic tests estimable projection if rank deficient; not a full53 restriction test. Cluster reference approximate and not clearance.'}
    pd.DataFrame(results).to_csv(TAB/'bassin_rd_estimates.csv',index=False)
    monthly_frame=pd.DataFrame(monthly)
    pre_mask=pd.to_datetime(monthly_frame.month).le('2023-05-01')
    monthly_frame.loc[pre_mask,'hc3_p_holm_53_pre']=multipletests(monthly_frame.loc[pre_mask,'p_hc3'],method='holm')[1]
    monthly_frame.to_csv(TAB/'bassin_rd_monthly_diagnostics.csv',index=False)
    pd.DataFrame(dependency).to_csv(TAB/'bassin_rd_dependency.csv',index=False)
    pd.DataFrame(official_checks).to_csv(REP/'bassin_rd_rbc_identity_checks.csv',index=False)
    report={'execution_freeze':freeze,'outcomes_now_read':True,'primary':next(r for r in results if r['period']=='primary_2024H2' and r['bandwidth']==1000),
            'pre_months':len(pre),'pre_joint_diagnostics':joint,'causal_clearance':False,
            'gate':'CLOSED_V_CAUSAL_ROUTE: historical discontinuities, selection composition jumps, concentrated dependencies',
            'q2_RBC_identity_verified':True,'component_limits':dependency}
    (REP/'bassin_rd_results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8')
    print(json.dumps({k:v for k,v in report.items() if k in ['primary','pre_joint_diagnostics','gate']},ensure_ascii=False),flush=True)

if __name__=='__main__':main()
